# Required, this config file format version
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: doc/OnlineDocs/source/conf.py

formats: all

python:
  install:
    - requirements: doc/OnlineDocs/requirements.txt

# Set the version of Python and requirements required to build the docs
#python:
#  version: 3

