name: prescient
channels:
- conda-forge
- defaults
dependencies:
- python>=3.7
- appdirs
- decorator
- networkx
- nose
- numpy
- pandas
# - pkg-resources
- ply
- python-dateutil
- pytz
- pyomo>=5.7.1
- scipy
- six
- ipopt
